#@data/values-schema
---
#@schema/nullable
name: local
components:
  - name: string

    #@schema/nullable
    pre_deploy_script: string

    #@schema/nullable
    post_deploy_script: string

    #@schema/nullable
    image: string

    #@schema/nullable
    skip_image_pull: true

    #@schema/type any=True
    env: null

    #@schema/nullable
    build_dev: string

    #@schema/nullable
    dependencies:
      - string

    deployments:
      #@schema/nullable
      - name: string

        #@schema/nullable
        image: string

        #@schema/nullable
        command: [string]

        #@schema/nullable
        ports:
          #@schema/nullable
          - port: 123

            #@schema/nullable
            hostPort: 123

        #@schema/type any=True
        env: null

        #@schema/nullable
        mount_path: string

        #@schema/nullable
        livenessProbe:
          #@schema/nullable
          exec:
            #@schema/nullable
            command: [string]

          #@schema/nullable
          httpGet:
            #@schema/nullable
            path: string

            #@schema/nullable
            port: 123

          #@schema/nullable
          initialDelaySeconds: 123

          #@schema/nullable
          periodSeconds: 123
